### PR TITLE
update the project to support new feature for latest mongodb version

### PR DESCRIPTION
**Pull request by guoyiwu**
1.Update the pom.xml file to support latest the library dependency because it is too old to compile correctly. 
2. Adjust the hierarchy of the src folder and make some modifications to adapt to the latest library dependency.  
3.Add authentication database and authenticate mechanism feature for latest mongodb version. 
4.comment off some functions in test due to some deprecated methods.

### CODE REVIEW

**Comment by guoyiwu** [comment]
It is my fault. The three files aren't working. I have deleted these files. please double check the pull request.

**Comment by maasdi** [comment]
Merge! Will prepare the package for new release

**Comment by guoyiwu** [comment]
Ok

**Comment by guoyiwu** [comment]
B.T.W
	To work normally for the plugin. It needs you to put mongo-java-driver-3.6.3.jar and pentaho-mongo-utils-8.2.0.0-SNAPSHOT.jar into the lib folder in the plugin.

**Comment by maasdi** [comment]
Yes, I know.
There is changes on pom.xml to automatically copy those libraries to pakage
folder

And FYI, new release package has been uploaded and available for manual
installation

Regards,
Maas

**Pull request merged**
